apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
namespace: ns-env-prod
configMapGenerator:
- envs:
  - configs/app-envs.env
  name: app-envs
- files:
  - configs/app-configs
  name: app-configs
components:
  - ../../../components/cluster-prod
