apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
configMapGenerator:
- envs:
  - configs/app-envs.env
  name: app-envs
  options:
    disableNameSuffixHash: true
- files:
  - configs/app-configs
  name: app-configs
  options:
    disableNameSuffixHash: true
components:
  - ../../../components/cluster-pt
generators:
- templateProcessor.yaml