apiVersion: v1
kind: ConfigMap
metadata:
  name: my-plugin-config
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: my-plugin
    spec:
      version: v1.0
      init:
        command:
          - sh
          - -c
          - "echo 'Initializing...'"
      generate:
        command:
          - sh
          - -c
          - "oc process --param-file=$PARAM_PARAMS_FILE -f . -o yaml --local"
      discover:
        fileName: "./*.yaml"
      parameters:
        static:
          - name: params-file
            title: Parameters file
            required: true
