apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cfg-mgt-component-test
spec:
  project: default
  source:
    repoURL: https://github.com/k-srkw/openshift-gitops-pattern
    targetRevision: HEAD
    path: configuration-management/components/overlays/cluster-prod/ns-env-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-env-prod
