apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
namespace: ns-env-1
# configs 配下のファイルから ConfigMap を作成する
configMapGenerator:
- envs:
  - configs/app-envs.env
  name: app-envs
- files:
  - configs/app-configs
  name: app-configs
components:
  - ../../../components/cluster-pt
