apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- envs:
  - configs/cluster-envs.env
  name: cluster-envs
  options:
    disableNameSuffixHash: true
- files:
  - configs/cluster-configs
  name: cluster-configs
  options:
    disableNameSuffixHash: true